language: c
group: stable
os: linux
before_install:
  - sudo add-apt-repository -y ppa:snaipewastaken/ppa
  - sudo apt-get update
  - sudo apt-get -y install criterion-dev

script:
  - make
  - make tests_run

notifications:
  email: false
